-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(*)
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog' OR ANIMAL_TYPE = 'Cat'
GROUP BY ANIMAL_TYPE
ORDER BY
    CASE ANIMAL_TYPE
        WHEN 'Cat' THEN 1
        WHEN 'Dog' THEN 2
        ELSE 3
    END