-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO B ON T.PARENT_ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO A ON T.ITEM_ID = A.ITEM_ID
WHERE B.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC