-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G USING(EMP_NO)
WHERE G.YEAR = 2022
GROUP BY G.EMP_NO
HAVING SCORE = (SELECT MAX(SUM_SCORE)
               FROM (SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
                    FROM HR_GRADE
                    WHERE YEAR = 2022
                    GROUP BY EMP_NO) AS T)